# Generated by Django 3.2.7 on 2021-09-29 02:46

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('url', models.URLField(null=True, verbose_name='网址')),
                ('content', mdeditor.fields.MDTextField(max_length=1000, verbose_name='内容')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
