# Generated by Django 3.2.7 on 2021-09-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log202003',
        ),
        migrations.DeleteModel(
            name='Log202004',
        ),
        migrations.DeleteModel(
            name='Log202005',
        ),
        migrations.DeleteModel(
            name='Log202006',
        ),
        migrations.DeleteModel(
            name='Log202007',
        ),
        migrations.DeleteModel(
            name='Log202008',
        ),
        migrations.DeleteModel(
            name='Log202009',
        ),
        migrations.DeleteModel(
            name='Log202010',
        ),
        migrations.DeleteModel(
            name='Log202011',
        ),
        migrations.DeleteModel(
            name='Log202012',
        ),
        migrations.DeleteModel(
            name='Log202101',
        ),
        migrations.DeleteModel(
            name='Log202102',
        ),
        migrations.DeleteModel(
            name='Log202103',
        ),
        migrations.DeleteModel(
            name='Log202104',
        ),
        migrations.DeleteModel(
            name='Log202105',
        ),
        migrations.DeleteModel(
            name='Log202106',
        ),
        migrations.DeleteModel(
            name='Log202107',
        ),
        migrations.DeleteModel(
            name='Log202108',
        ),
    ]
