# Generated by Django 3.2.7 on 2021-09-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_log202003_log202004_log202005_log202006_log202007_log202008_log202009_log202010_log202011_log202012_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log202003',
        ),
        migrations.DeleteModel(
            name='Log202004',
        ),
        migrations.DeleteModel(
            name='Log202005',
        ),
        migrations.DeleteModel(
            name='Log202006',
        ),
        migrations.DeleteModel(
            name='Log202007',
        ),
        migrations.DeleteModel(
            name='Log202008',
        ),
        migrations.DeleteModel(
            name='Log202009',
        ),
        migrations.DeleteModel(
            name='Log202010',
        ),
        migrations.DeleteModel(
            name='Log202011',
        ),
        migrations.DeleteModel(
            name='Log202012',
        ),
        migrations.DeleteModel(
            name='Log202101',
        ),
        migrations.DeleteModel(
            name='Log202102',
        ),
        migrations.DeleteModel(
            name='Log202103',
        ),
        migrations.DeleteModel(
            name='Log202104',
        ),
        migrations.DeleteModel(
            name='Log202105',
        ),
        migrations.DeleteModel(
            name='Log202106',
        ),
        migrations.DeleteModel(
            name='Log202107',
        ),
        migrations.DeleteModel(
            name='User5',
        ),
        migrations.DeleteModel(
            name='User6',
        ),
        migrations.DeleteModel(
            name='User7',
        ),
        migrations.DeleteModel(
            name='User8',
        ),
        migrations.DeleteModel(
            name='User9',
        ),
    ]
